version: '3'

services:
  nginx:
    container_name: pelayanan-desa-nginx
    build:
      context: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
  php:
    container_name: pelayanan-desa-php
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    user: bimantara
    volumes:
      - ./:/usr/share/nginx/html
  mysql:
    container_name: pelayanan-desa-mysql
    build:
      context: ./docker/mysql
    ports:
      - 33061:3306
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: b1sm1ll4h
      MYSQL_DATABASE: tabungan_sekolah
  phpmyadmin:
    container_name: pelayanan-desa-phpmyadmin
    build:
      context: ./docker/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - ./:/usr/share/nginx/html
